[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1-PSCA65YC1HOQ5fHDKvu-0gPbDXG7pxp64OxYspXhvk/edit"
type = "service_account"
project_id = "language-translator-484004"
private_key_id = "7d7a3ed06de22d4de05fd2f92e144e474272f401"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMeGcZlKSTHSUg
l7HnUNLtmRpI6se377NxgOvFZHZdDbsQsc426v60wwCh9jhjIwKaxc4Oxgou/ERX
KtMQKBavHP2UrPvyg3cd92dPX0OByf5tWyyHmWGRazeZeRxUsRZ3esaJXXJoJBMX
DQKjSAGI94x80xcyx/70iR/AVJE5eKnoU0QkIA9LCJiYrB+NXuYSlqTbMoryqY93
Hay4hSoqVKRgN+4L2IuNeDDavFzHOzvM6o0nE122KxwRXph4uC2ONM+D3aCdIVqU
PyGeA/pjKo3i28emmlT7BcA8j02PJk1rzlRoDD5RGO/9iM9elLwYP55UYiIeaWTE
SS3rKraDAgMBAAECggEAUZ7KgSKd43/h3zXOtWjFGkVggbT+zoTn26o784rb2N9v
SgXALJn33M5uxThVX/WMx52oWKtjS0g2O5mDsVJfY72t2BiJZlBmT1cALWX4u6mX
X63ig6qNkQ/8nM4EqiYass0WzaS406t611vBLs7ClhtDQFy/SO0e8ByAyTS41/iE
2OzNbQDJ5pG+JY56y7BKzBS3CNWpxLbPTQ3RXtIOupykLekXqq8NvfNZxYH4sTQR
+W54GsVnkC9TJEGugaJlvDbSe0yt/AisufXbrxvOQEn/KSVT5ptW7pghn7wZeZax
DEJZkDzi+1UcYYnu8qBWTkTS49bMWihNEn4TOqxtUQKBgQDyqsBywtcUAeswzXBa
iYUDx2DE3RTm9mPlofdWkNNVIswFYmwAKQyaiP18Oaoo9ZEakklN+5wOiLMVy8aG
gZFNlb+p4JE0uhngcrLanXHjWVRREQTKloPCJVs3nelW8Aq6joVM0pBgWX75LN8J
CTX sY7Gb4PTrNxJR4jniPU9GiQKBgQDXtGSn7ifoR07aynRMHOG3qgwM5KgesVGh
iSnp9a0tup2VcfBQ6v/rDtxjQ36L0Z4zECz/tUVmUI+awJIkd4KNWtiPvdNaCnBh
b5UCceb3Zpn+R16OpKt0oJQw7EAffTL5ees3mw6l9lkUMdws5nVClPIzzYF3/OQt
5KlIrWuRqwKBgE6fyG7mdi1DWeKcDZUoDXLl/JKMVyNmHYPfcHYZwn9JIPV1qCx9
IFpJnGfNfzZ6KiOD1kBwD2YeIHglaBNYk62hoVH3MtT0n0G7p/txG99fqBQEAZtq
HRKga+efQGUsrS041DPJ3YF6PcuaIEGbPF91BazNvE0hsMvbEooc9zyRAoGAVqhh
W9ng7H9hXaLCUCW2RMwrJS7jn9kK+4OYdCbAGUQEtRpeOpP+lpeU0Mg32cIv9UHF
YkGYDP/GgZxl2gKtT060/CJ9+4mAFpT2X1IVQUVWDoLrqRDc1PECOBlhtYTd6r4h
UmiX3PL4XJWfZ+Z6K3KdT1R7dBIENa/MlqcdNRsCgYEAiU07jUSM0woVGaU77HyU
Geb+H9FTTOvsPVEVsNZGVUpXP7x0UMi2ZTM8w2n5A+7V/OMkYCJPQVA2Zm499pko
NOlLAV0947AVbtSr3sTGU7wldXFWSy8sOCXex2kfRuNXRdvGiXV/V4YRrbt0vWK2
RdCt7xg9EijzEgomruxsCoU=
-----END PRIVATE KEY-----"""
client_email = "streamlit-translator-199@language-translator-484004.iam.gserviceaccount.com"
client_id = "114984233507710506594"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-translator-199%40language-translator-484004.iam.gserviceaccount.com"
universe_domain = "googleapis.com"